import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert';
const context={window:{},document:{getElementById(){return null},addEventListener(){}}};vm.runInNewContext(fs.readFileSync('public/assets/js/custom-dashboard.js','utf8'),context);const select=context.window.BADMAAL_IR_MODEL.selectRows;
const years=['FY25','FY26','FY27','FY28','FY29','FY30'],codes=['IR1','IR2','IR2a','IR3','IR4','IR5','IR5a','IR6','IR7','IR8','IR9','IR10','IR11'],rows=[];
for(const code of codes)for(const year of years)rows.push({type:'IR',code,parentCode:code.endsWith('a')?code.slice(0,-1):null,component:['IR1','IR2','IR2a','IR3'].includes(code)?'Component 1':code==='IR11'?'Component 3':'Component 2',year,state:null,target:code==='IR3'&&year!=='FY27'&&year!=='FY30'?null:10,result:null,reportedAt:null,period:null});
for(const year of years){const selected=select(rows,{year,component:'All',state:'All'});assert.strictEqual(selected.length,13);assert.strictEqual(selected.filter(x=>x.result!==null).length,0)}
rows.push({...rows.find(x=>x.code==='IR1'&&x.year==='FY25'),state:'National',result:0,reportedAt:'2025-06-30',period:'Annual'});rows.push({...rows.find(x=>x.code==='IR1'&&x.year==='FY26'),state:'National',result:8,reportedAt:'2026-06-30',period:'Annual'});
let selected=select(rows,{year:'All',component:'All',state:'All'});assert.strictEqual(selected.find(x=>x.code==='IR1').year,'FY26');assert.strictEqual(selected.find(x=>x.code==='IR1').result,8);assert.strictEqual(select(rows,{year:'FY27',component:'Component 1',state:'All'}).length,4);assert.strictEqual(select(rows,{year:'FY27',component:'Component 2',state:'All'}).length,8);assert.strictEqual(select(rows,{year:'FY27',component:'Component 3',state:'All'}).length,1);
selected=select(rows,{year:'FY26',component:'All',state:'Galmudug'});assert.strictEqual(selected.length,13);assert.strictEqual(selected.filter(x=>x.result!==null).length,0);
rows.push({...rows.find(x=>x.code==='IR4'&&x.year==='FY26'),state:'Galmudug',result:1,reportedAt:'2026-05-01',period:'Q3'});rows.push({...rows.find(x=>x.code==='IR4'&&x.year==='FY26'),state:'Galmudug',result:2,reportedAt:'2026-06-01',period:'Q4'});rows.push({...rows.find(x=>x.code==='IR4'&&x.year==='FY26'),state:'National',result:6,reportedAt:'2026-06-30',period:'Annual'});
selected=select(rows,{year:'FY26',component:'All',state:'Galmudug'});assert.strictEqual(selected.find(x=>x.code==='IR4').result,2);assert.strictEqual(selected.find(x=>x.code==='IR4').state,'Galmudug');
selected=select(rows,{year:'FY26',component:'All',state:'All'});assert.strictEqual(selected.find(x=>x.code==='IR4').result,6);assert.strictEqual(selected.find(x=>x.code==='IR4').state,'National');
console.log('IR fiscal-year/filter model tests passed.');
