<?php
require dirname(__DIR__).'/app/web.php';requireAuth();requireAnyPermission(['grm.view']);
$id=max(0,(int)($_GET['id']??0));$case=null;$categories=[];
if($id){$s=db()->prepare('SELECT * FROM grievances WHERE id=?');$s->execute([$id]);$case=$s->fetch();if(!$case){http_response_code(404);exit('Case not found.');}$s=db()->prepare('SELECT category FROM grievance_categories WHERE grievance_id=? ORDER BY category');$s->execute([$id]);$categories=$s->fetchAll(PDO::FETCH_COLUMN);audit('grm_case_viewed',[],$id);}
$states=['received','pending','under_review','resolved','closed','archived','submitted'];$priorities=['low','medium','high','urgent'];
$status=in_array($_GET['status']??'',$states,true)?$_GET['status']:'';$priority=in_array($_GET['priority']??'',$priorities,true)?$_GET['priority']:'';
$page=max(1,(int)($_GET['page']??1));$where=[];$args=[];if($status!==''){$where[]='status=?';$args[]=$status;}if($priority!==''){$where[]='priority=?';$args[]=$priority;}
$where=$where?' WHERE '.implode(' AND ',$where):'';$s=db()->prepare('SELECT COUNT(*) FROM grievances'.$where);$s->execute($args);$count=(int)$s->fetchColumn();
$s=db()->prepare('SELECT id,external_id,subject,status,priority,region,submitted_at FROM grievances'.$where.' ORDER BY id DESC LIMIT 20 OFFSET '.(($page-1)*20));$s->execute($args);$rows=$s->fetchAll();
pageStart($case?'GRM case #'.$id:'GRM cases','grievances.php');
?><?php if(isset($_GET['saved'])):?><p class="notice">Case saved successfully.</p><?php endif;?><?php if(hasAnyPermission(['grm.manage'])):?><div class="actions" style="margin-bottom:20px"><a class="button" href="/grm-entry.php">New GRM case</a><?php if($case):?><a class="button" href="/grm-entry.php?id=<?=$id?>">Edit case</a><?php endif;?></div><?php endif;?><?php if($case):?><section class="card"><div class="actions"><a href="/grievances.php">← All cases</a><span class="badge"><?=e($case['status'])?></span><span class="badge"><?=e($case['priority'])?> priority</span></div><h2 style="margin-top:20px"><?=e($case['subject']?:'Case #'.$id)?></h2><p><strong>Reference:</strong> <?=e($case['external_id']??$id)?></p><p><strong>Categories:</strong> <?=e(implode(', ',$categories))?></p><div class="two"><?php foreach(['complainant_name'=>'Complainant','email'=>'Email','phone'=>'Phone','region'=>'Region','district'=>'District','incident_date'=>'Incident date','people_affected'=>'People affected','preferred_followup'=>'Preferred follow-up','submitted_at'=>'Submitted','response_at'=>'Responded','created_at'=>'Created','updated_at'=>'Updated'] as $field=>$label):?><p><strong><?=e($label)?>:</strong><br><?=e($case[$field]??'—')?></p><?php endforeach;?></div><?php foreach(['description'=>'Description','review_comments'=>'Review comments','response'=>'Response'] as $field=>$label):?><h2><?=e($label)?></h2><p style="white-space:pre-wrap;overflow-wrap:anywhere"><?=e($case[$field]?:'None recorded')?></p><?php endforeach;?><?php
$s=db()->prepare('SELECT 1 FROM grm_evidence_files WHERE grievance_id=?');$s->execute([$id]);if($s->fetchColumn()):?><a class="button" href="/grm-evidence.php?id=<?=$id?>">Download private evidence</a><?php endif;?></section>
<section class="card"><h2>Case attribution</h2><?php foreach(['created_by'=>'Created by','updated_by'=>'Updated by','response_by'=>'Responded by','reviewed_by'=>'Reviewed by','approved_by'=>'Approved by','published_by'=>'Published by'] as $field=>$label):if(!$case[$field])continue;$s=db()->prepare('SELECT username FROM users WHERE id=?');$s->execute([$case[$field]]);?><p><strong><?=e($label)?>:</strong> <?=e($s->fetchColumn()?:'Historical user #'.$case[$field])?></p><?php endforeach;?><p class="muted">Original attribution is retained. Updates record the responsible staff member and a before-and-after audit history.</p></section><?php else:?>
<form method="get" class="card filters"><label>Status<select name="status"><option value="">All statuses</option><?php foreach($states as $v):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=e(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label><label>Priority<select name="priority"><option value="">All priorities</option><?php foreach($priorities as $v):?><option <?=$priority===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><button>Filter</button><a href="/grievances.php">Clear</a></form>
<section class="card"><h2><?=$count?> cases</h2><div class="table-scroll"><table><thead><tr><th>Reference / subject</th><th>Region</th><th>Status</th><th>Priority</th><th>Submitted</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><a href="?id=<?=$r['id']?>"><?=e($r['external_id']?:'#'.$r['id'])?></a><br><?=e($r['subject'])?></td><td><?=e($r['region'])?></td><td><?=e($r['status'])?></td><td><?=e($r['priority'])?></td><td><?=e($r['submitted_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$rows):?><p>No matching cases.</p><?php endif;?><nav class="pagination"><?php foreach([$page-1=>'Previous',$page+1=>'Next'] as $p=>$label):if($p<1||($p-1)*20>=$count)continue;?><a href="?<?=e(http_build_query(['status'=>$status,'priority'=>$priority,'page'=>$p]))?>"><?=$label?></a><?php endforeach;?></nav></section><?php endif;?><?php pageEnd();?>
