<?php
declare(strict_types=1);
namespace App\Repositories;
use PDO;

final class MisRepository {
    public function __construct(private PDO $pdo, private bool $publishedOnly = false) {}
    private function publishedFilter(string $module, string $id): string {
        if (!$this->publishedOnly) return '';
        try { $this->pdo->query('SELECT 1 FROM mis_publications LIMIT 1'); }
        catch (\Throwable) { return ' AND 1=0'; }
        return " AND EXISTS (SELECT 1 FROM mis_publications publication WHERE publication.module='".$module."' AND publication.record_id=".$id." AND publication.revision>0)";
    }
    public function isInstalled(): bool { try { $this->pdo->query('SELECT 1 FROM mis_indicators LIMIT 1'); return true; } catch (\Throwable) { return false; } }
    public function indicators(?string $type=null): array { $sql='SELECT i.*,p.id period_id,p.fiscal_year,p.reporting_period,p.state,p.target_value,p.actual_value,p.status,p.reported_at FROM mis_indicators i LEFT JOIN mis_indicator_periods p ON p.indicator_id=i.id WHERE i.is_active=1'; $args=[]; if($type){$sql.=' AND i.indicator_type=?';$args[]=$type;} $sql.=' ORDER BY i.indicator_type DESC,i.code,p.fiscal_year';$s=$this->pdo->prepare($sql);$s->execute($args);return $s->fetchAll(); }
    public function pdoIndicators(): array { $sql="SELECT i.*,y.fiscal_year,NULL reporting_period,NULL state,(SELECT p.target_value FROM mis_indicator_periods p WHERE p.indicator_id=i.id AND p.fiscal_year=y.fiscal_year AND p.state='National' AND p.target_value IS NOT NULL ORDER BY p.reporting_period='Annual' DESC,p.reported_at DESC LIMIT 1) target_value,NULL actual_value,NULL reported_at FROM mis_indicators i CROSS JOIN (SELECT 'FY25' fiscal_year UNION ALL SELECT 'FY26' UNION ALL SELECT 'FY27' UNION ALL SELECT 'FY28' UNION ALL SELECT 'FY29' UNION ALL SELECT 'FY30') y WHERE i.is_active=1 AND i.indicator_type='PDO' AND i.parent_code IS NULL UNION ALL SELECT i.*,p.fiscal_year,p.reporting_period,p.state,p.target_value,p.actual_value,p.reported_at FROM mis_indicators i JOIN mis_indicator_periods p ON p.indicator_id=i.id WHERE i.is_active=1 AND i.indicator_type='PDO' AND i.parent_code IS NULL AND p.actual_value IS NOT NULL".$this->publishedFilter('indicators','p.id')." ORDER BY code,fiscal_year,reported_at,reporting_period";$s=$this->pdo->prepare($sql);$s->execute();return $s->fetchAll(); }
    public function irIndicators(): array { $sql="SELECT i.*,y.fiscal_year,NULL reporting_period,NULL state,(SELECT p.target_value FROM mis_indicator_periods p WHERE p.indicator_id=i.id AND p.fiscal_year=y.fiscal_year AND p.state='National' AND p.target_value IS NOT NULL ORDER BY p.reporting_period='Annual' DESC,p.reported_at DESC LIMIT 1) target_value,NULL actual_value,NULL reported_at FROM mis_indicators i CROSS JOIN (SELECT 'FY25' fiscal_year UNION ALL SELECT 'FY26' UNION ALL SELECT 'FY27' UNION ALL SELECT 'FY28' UNION ALL SELECT 'FY29' UNION ALL SELECT 'FY30') y WHERE i.is_active=1 AND i.indicator_type='IR' UNION ALL SELECT i.*,p.fiscal_year,p.reporting_period,p.state,p.target_value,p.actual_value,p.reported_at FROM mis_indicators i JOIN mis_indicator_periods p ON p.indicator_id=i.id WHERE i.is_active=1 AND i.indicator_type='IR' AND p.actual_value IS NOT NULL".$this->publishedFilter('indicators','p.id')." ORDER BY code,fiscal_year,reported_at,reporting_period";$s=$this->pdo->prepare($sql);$s->execute();return $s->fetchAll(); }
    public function indicatorById(int $id): ?array { $s=$this->pdo->prepare('SELECT * FROM mis_indicators WHERE id=? AND is_active=1');$s->execute([$id]);$row=$s->fetch();return $row?:null; }
    public function indicatorTargetForYear(int $indicatorId,string $fiscalYear): ?float { $s=$this->pdo->prepare("SELECT target_value FROM mis_indicator_periods WHERE indicator_id=? AND fiscal_year=? AND state='National' AND target_value IS NOT NULL ORDER BY reporting_period='Annual' DESC,reported_at DESC LIMIT 1");$s->execute([$indicatorId,$fiscalYear]);$value=$s->fetchColumn();return $value===false||$value===null?null:(float)$value; }
    public function updatePdo5Baseline(float $value,string $referenceDate,string $source,int $user): void { $s=$this->pdo->prepare("UPDATE mis_indicators SET baseline_value=?,baseline_date=?,data_source=?,updated_by=? WHERE code='PDO5' AND indicator_type='PDO' AND parent_code IS NULL");$s->execute([$value,$referenceDate,$source,$user]);if($s->rowCount()===0&&!$this->indicatorByCodeExists('PDO5'))throw new \RuntimeException('PDO5 metadata is not installed.'); }
    private function indicatorByCodeExists(string $code): bool { $s=$this->pdo->prepare('SELECT 1 FROM mis_indicators WHERE code=? LIMIT 1');$s->execute([$code]);return (bool)$s->fetchColumn(); }
    public function contracts(): array { return $this->pdo->query('SELECT * FROM mis_contracts WHERE 1=1'.$this->publishedFilter('contracts','mis_contracts.id').' ORDER BY updated_at DESC')->fetchAll(); }
    public function finances(): array { return $this->pdo->query('SELECT * FROM mis_financial_records WHERE 1=1'.$this->publishedFilter('finance','mis_financial_records.id').' ORDER BY fiscal_year DESC,quarter,component')->fetchAll(); }
    public function saveIndicatorPeriod(array $d,int $user): void { $s=$this->pdo->prepare("INSERT INTO mis_indicator_periods(indicator_id,fiscal_year,reporting_period,state,target_value,actual_value,status,notes,reported_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE target_value=VALUES(target_value),actual_value=VALUES(actual_value),status=VALUES(status),notes=VALUES(notes),reported_at=VALUES(reported_at),updated_by=VALUES(updated_by)");$s->execute([$d['indicator_id'],$d['fiscal_year'],$d['reporting_period'],$d['state'],$d['target_value'],$d['actual_value'],$d['status'],$d['notes'],$d['reported_at']?:null,$user,$user]); }
    public function saveContract(array $d,int $user): void { $s=$this->pdo->prepare("INSERT INTO mis_contracts(reference_no,title,component,contractor,state,contract_value,paid_amount,progress_percent,start_date,end_date,status,notes,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),component=VALUES(component),contractor=VALUES(contractor),state=VALUES(state),contract_value=VALUES(contract_value),paid_amount=VALUES(paid_amount),progress_percent=VALUES(progress_percent),start_date=VALUES(start_date),end_date=VALUES(end_date),status=VALUES(status),notes=VALUES(notes),updated_by=VALUES(updated_by)");$s->execute([$d['reference_no'],$d['title'],$d['component'],$d['contractor'],$d['state'],$d['contract_value'],$d['paid_amount'],$d['progress_percent'],$d['start_date']?:null,$d['end_date']?:null,$d['status'],$d['notes'],$user,$user]); }
    public function saveFinance(array $d,int $user): void { $s=$this->pdo->prepare("INSERT INTO mis_financial_records(fiscal_year,quarter,component,budget_amount,committed_amount,disbursed_amount,expenditure_amount,notes,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE budget_amount=VALUES(budget_amount),committed_amount=VALUES(committed_amount),disbursed_amount=VALUES(disbursed_amount),expenditure_amount=VALUES(expenditure_amount),notes=VALUES(notes),updated_by=VALUES(updated_by)");$s->execute([$d['fiscal_year'],$d['quarter'],$d['component'],$d['budget_amount'],$d['committed_amount'],$d['disbursed_amount'],$d['expenditure_amount'],$d['notes'],$user,$user]); }
}
